### ISSUE TITLE
App hangs after it tries to load themes...

### ISSUE THREAD

**Issue by bjutla** [meeech/Shopify-Theme-Tool#25]
Hi! 

The app is hanging ever since I upgraded to Yosemite, when I try to load themes - whether you add a new store or a store is already loaded.

I went through the issue up to Level 2 Support at Shopify but they couldn't figure it out, the app worked when I created a new user on my machine, so it is likely be something on my profile. I've tried App Zapper and cleared all the preferences files (com.meeech.* files) in the ~/Library directories.

From the logfile:
[21:18:21:201] [Ti.Network.HTTPClient] [Error] Failed for URL ... my-store-name.myshopify.com/admin/themes.json): SSL peer certificate or SSH remote key was not OK

I can email the rest over if you'd like.

**Comment by meeech** [comment]
Hey balraj 

Yes email the log over to me

**Comment by bjutla** [comment]
Hi Mitchell

Thanks for taking a look into this!

Cheers,

-- 
Balraj Jutla
Creative Crisp

**Comment by bjutla** [comment]
Hi Mitchell,

I looked through the resource  you found at:
https://wordpress.org/support/topic/download-failed-ssl-peer-certificate-or-ssh-remote-key-was-not-ok

I noticed that these users had to reset their hosts db on their servers, however being on my local machine, I searched how to reset the OS X SSL settings and found that:

To resolve this issue I ended up having to reset my Keychain Access App on OS X
Keychain.app > Preferences > General > Reset My Default Keychain

A note to other users, this should not delete your other saved passwords, just resets your "Login" profile.

Cheers!
Balraj
